### ISSUE TITLE
[BUG] Uploading documents with Tags fails with Paperless-ngx 2.0.0

### ISSUE THREAD

**Issue by slydlake** [LeoKlaus/Paperparrot#158] opened 2023-11-23 11:13 UTC
Hi,

maybe this is a problem with the new paperless 2.0 RC1, but I have a strange problem with uploading a document in the App

**To Reproduce**
1. Open App
2. Go to "Add" tab
3. upload from files app (also when I scan from a network scanner)
4. Select document
5. Now it is showing me the fields, didn't change anything, go to upload
6. Error prompts immediately "'NoneType' object is not iterable"

BUT it works when I do this:
1. Open iOS File app App
2. open Document
3. "Share" -> Paperparrot
4. Now it is showing the title (didn't change anything), go to upload
5. Now it will upload and it works!

**Environment:**
 - Device: iPhone 13
 - OS: iOS 17.1.1
 - Server Version  Paperless-ngx 2.0.0-beta.rc1

**Additional context**
Log file from Uploading from iOS App:

`[2023-11-23 11:57:43,590] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[743bb832-61bd-4a8a-9432-4cd54f81a49c] received
[2023-11-23 11:57:44,883] [WARNING] [paperless.barcodes] No pages to split on!
[2023-11-23 11:57:46,057] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[743bb832-61bd-4a8a-9432-4cd54f81a49c] raised unexpected: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/tasks.py", line 164, in consume_file
    overrides.update(template_overrides)
  File "/usr/src/paperless/src/documents/data_models.py", line 56, in update
    self.tag_ids.extend(other.tag_ids)
TypeError: 'NoneType' object is not iterable
/usr/local/lib/python3.11/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(`

Log file from Uploading from Mac App:

`[2023-11-23 12:03:03,214] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[dff0411d-d777-4603-bc1e-30768b7ae489] received
[2023-11-23 12:03:04,575] [WARNING] [paperless.barcodes] No pages to split on!
[2023-11-23 12:03:05,737] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[dff0411d-d777-4603-bc1e-30768b7ae489] raised unexpected: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/tasks.py", line 164, in consume_file
    overrides.update(template_overrides)
  File "/usr/src/paperless/src/documents/data_models.py", line 56, in update
    self.tag_ids.extend(other.tag_ids)
TypeError: 'NoneType' object is not iterable`

Log file from Uploading it with the "Share" Menu in the iOS File App: (please ignore the errors here, my RAM is a little bit too low)

`[2023-11-23 11:49:04,891] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[33f3cb73-c2c1-4c5b-b1f1-91bd2e961fd3] received
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=31 f=-1(000) part=1
[2023-11-23 11:50:00,031] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2023-11-23 11:50:00,046] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[ea0efa17-aacb-4f32-99db-5f90c0e8fd19] received
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=17 f=-1(000) part=0
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=21 f=-1(000) part=0
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=16 f=-1(000) part=0
/usr/local/lib/python3.11/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
[2023-11-23 11:52:16 +0100] [189] [CRITICAL] WORKER TIMEOUT (pid:84509)
[2023-11-23 11:53:01 +0100] [189] [ERROR] Worker (pid:84509) was sent SIGKILL! Perhaps out of memory?
[2023-11-23 11:53:18,013] [WARNING] [paperless.barcodes] No pages to split on!
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=31 f=-1(000) part=1
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=17 f=-1(000) part=0
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=21 f=-1(000) part=0
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=16 f=-1(000) part=0
[2023-11-23 11:54:54,737] [INFO] [paperless.consumer] Consuming EVPS00202311202035013820600.pdf
[2023-11-23 11:55:01,379] [WARNING] [ocrmypdf._pipeline] This PDF is marked as a Tagged PDF. This often indicates that the PDF was generated from an office document and does not need OCR. PDF pages processed by OCRmyPDF may not be tagged correctly.
[2023-11-23 11:55:01,380] [INFO] [ocrmypdf._pipelines.ocr] Start processing 4 pages concurrently
[2023-11-23 11:55:01,393] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,394] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,395] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,396] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,396] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,399] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,399] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,400] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,401] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,401] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,401] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,402] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,403] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,403] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,404] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,404] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,405] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,405] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,405] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,406] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,407] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,407] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,407] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,408] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:01,409] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-11-23 11:55:02,119] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[2023-11-23 11:55:03,921] [WARNING] [ocrmypdf._metadata] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
[2023-11-23 11:55:04,322] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.01 savings: 1.1%
[2023-11-23 11:55:04,323] [INFO] [ocrmypdf._pipeline] Total file size ratio: 3.64 savings: 72.5%
[2023-11-23 11:55:04,367] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
/usr/local/lib/python3.11/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
[2023-11-23 11:55:19,285] [INFO] [paperless.handlers] Assigning correspondent o_Versicherungen to 2023-11-20 EVPS00202311202035013820600
[2023-11-23 11:55:19,461] [INFO] [paperless.handlers] Assigning document type Unterlage to 2023-11-20 o_Versicherungen EVPS00202311202035013820600
[2023-11-23 11:55:20,298] [INFO] [paperless.consumer] Document 2023-11-20 o_Versicherungen EVPS00202311202035013820600 consumption finished
[2023-11-23 11:55:20,321] [INFO] [celery.app.trace] Task documents.tasks.consume_file[33f3cb73-c2c1-4c5b-b1f1-91bd2e961fd3] succeeded in 375.42055592499673s: 'Success. New document id 202 created'
`

Thank you very much ☺️

**Comment by LeoKlaus** [comment] 2023-11-23 11:16
Hi Timon,

thank you for all the information. Are you in the TestFlight beta for Paperparrot or are you using the AppStore version?

I'll check whether I can reproduce this.

**Comment by slydlake** [comment] 2023-11-23 11:39
Just using the App Store version. Where can I find the TestFlight link?

**Comment by LeoKlaus** [comment] 2023-11-23 12:55
The TestFlight beta is currently not public/open. You can just send me a message on Discord or at support@paperparrot.me if you want to join.

I've just tried uploading a document and can reproduce the issue on my test instance on Paperless-ngx 2.0.0 RC1. The same also applies to the 2.0.0 beta of Paperparrot.

I'll have a closer look at what's causing this and let you know once I know more.

**Comment by LeoKlaus** [comment] 2023-11-23 14:23
I can confirm this is a bug in Paperless-ngx 2.0.0 RC 1 and is caused by the `tags` part of the multipart form sent by Paperparrot.

I've created an issue regarding this at paperless-ngx/paperless-ngx#4666

A temporary workaround is to remove all tags in Paperparrot before posting a document.

I'll leave this open for now so others can see this is a known issue.

**Comment by LeoKlaus** [comment] 2023-11-23 15:24
This was already fixed in the latest beta image of Paperless-ngx 2.0.0.
Just switch to the "beta" tag for the docker image, pull and recreate.

**Closed as completed by LeoKlaus** 2023-11-23 15:24 UTC
Labels: bug

**Comment by slydlake** [comment] 2023-11-23 16:52
Yes can confirm that the newest beta is now working 👍
