### ISSUE TITLE
[BUG] I am not able to upload documents from scan anymore

### ISSUE THREAD

**Issue by Piste** [LeoKlaus/Paperparrot#124] opened 2023-09-18 01:30 UTC
**Describe the bug**
I go to upload, the app captures automatically, I change the name and click upload. It instantly sends me to the four "add" tiles menu and my document cannot be found on the server. There is no display showing that files are being uploaded.

**To Reproduce**
See above

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17
 - Version 1.17.0
 - Server Version (if applicable) [e.g. Paperless-ngx 1.11.3]: not sure how to find this out

I'm not sure how to troubleshoot this.

**Comment by LeoKlaus** [comment] 2023-09-18 07:17
Hi Piste, thank you for the bug report. I'm sorry for the inconvenience.

I'm assuming you're using Paperparrot with a Paperless-ngx server you host yourself, if you're not, please let me know.

I can't reproduce this bug on my devices/servers. With Paperparrot 1.4.0, the upload process has changed slightly and should look like this (it doesn't matter whether the document is scanned with the camera or uploaded from files):
![Simulator Screen Recording - iPhone 15 Pro - 2023-09-18 at 09 09 27](https://github.com/LeoKlaus/Paperparrot/assets/66492595/2dccfa99-fd0d-400c-9e5b-407a78a493a5)

If no server tasks appear after uploading the file, please check the file tasks section in Paperless-ngx for failed tasks regarding your document.
![Screenshot 2023-09-18 at 09 13 17](https://github.com/LeoKlaus/Paperparrot/assets/66492595/eea94af2-faf6-4d2d-ae64-0e9cb7019569)
![Screenshot 2023-09-18 at 09 13 32](https://github.com/LeoKlaus/Paperparrot/assets/66492595/f291c80c-0399-4f40-b993-4d7f06df3876)

The version number for your Paperless server is in the bottom left corner of the webinterface, the version number for Paperparrot can be found at the bottom in Settings->About Paperarrot.

**Comment by Piste** [comment] 2023-09-20 12:31
> Paperparrot with a Paperless-ngx server you host yourself

Correct. Via Tailscale.

the file tasks section does not have anything relevant to anything recently submitted by the app.

PaperParrot v.1.7.2
Paperless NGX v.1.17.4 but PaperParrot thinks it's v.1.17.0

---

In order to troubleshoot, I have disconnected the existing server and tried to enter it again. Now PaperParrot won't connect to the server anymore. I use `http://{tailscale-IP}:{port}/` and the same user and password as for the UI. This used to work (see #103)

**Comment by LeoKlaus** [comment] 2023-09-20 12:48
That is curious. Sounds like Paperparrot cant manage to connect at all. 
Please try connecting to `http://{tailscale-IP}:{port}` (without the trailing slash).

Did you change any permissions in Paperless recently? Can you reach `http://{tailscale-IP}:{port}/api/documents/` in your browser with the same credentials?

**Comment by Piste** [comment] 2023-09-20 19:56
`http://{tailscale-IP}:{port}/api/documents/` resolves to a 404. I can see how this would be a problem.
I don't remember changing anything other than updating the paperless-ngx docker image. I'm not sure where the Paperless permissions would be. If Django, then I haven't touched them. Happy to compare my settings against what's expected.

**Comment by Piste** [comment] 2023-09-20 19:57
`http://{tailscale-IP}:{port}/api/` resolves without a problem and when I click on the `/api/documents/` endpoint it does work. So weird.

**Comment by Piste** [comment] 2023-09-20 19:59
I'll have a deep dive into the docker compose permission parameters

**Comment by Piste** [comment] 2023-09-20 22:54
okay I'm back. I had a postgres update to resolve first on paperless but now all containers are up and steady.
Browsing to `http://{tailscale-IP}:{port}/api/documents/` now works but I'm still getting a "Couldn't connect to server" in Paperparrot.
I am not seeing anything in the paperless log but I did see a message in the log when I tried to curl `/api/documents/` which confirms the server is doing what it should be doing. 
iPhone reboot didn't help

**Comment by LeoKlaus** [comment] 2023-09-21 08:50
Thank you for all the information. Sounds like there is still some issue preventing Paperparrot from connecting to your instance.
Can you try running

``` bash
curl -X POST http://{tailscale-IP}:{port}/api/token/ \
   -H 'Content-Type: application/json' \
   -d '{"username":"{your_user}","password":"{your_pass}"}'
```

The response should look like this:

``` JSON
{
  "token": "79xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxcc"
}
```

You can use that token to then make another request (replace the token with the one your instance returned):

``` bash
curl -X GET http://{tailscale-IP}:{port}/api/documents/ \
   -H 'Content-Type: application/json' \
   -H 'Authorization:Token 79xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxcc'
```

Does your server return documents that way?

**Comment by Piste** [comment] 2023-09-30 03:06
It does. The first command gives me a token, indeed. And the second command returns documents.
(thanks for your patience by the way)

**Comment by Piste** [comment] 2023-09-30 03:09
The iOS paperless app was able to log me in...

**Comment by LeoKlaus** [comment] 2023-10-02 07:26
That's super weird. Have you tried reinstalling Paperparrot? It really shouldn't make a difference, but maybe something got stuck hard.

I plan to include debug logging with the next update, but it might take a while until that is ready.
I'm really sorry for the inconvenience.

**Comment by LeoKlaus** [comment] 2023-10-04 12:03
It seems that Paperparrot currently has issues with Tailscale.
Either Tailscale or iOS 17 seemingly have changed how connections are handled, as Paperparrot only uses standard iOS URLSessions.

I've created a separate issue at #131 to collect all connectivity problems in combination with Tailscale, so I'm closing this one for now. I haven't forgotten about you and am actively working on a fix.

**Closed as not planned** 2023-10-04 12:03 UTC
Labels: bug
