### ISSUE TITLE
[BUG] iCloud Sync Error on version 2.1.2

### ISSUE THREAD

**Issue by nerdware-timmmi** [LeoKlaus/Paperparrot#176] opened 2024-01-10 12:47 UTC
**Describe the bug**
I cannot sync a document from my IPad to my IPhone

Similiar issue maybe here?: https://github.com/LeoKlaus/Paperparrot/issues/141
My version is 2.1.2 on both devices.

**To Reproduce**
- add a pdf from iCloud finder app on my IPad
- try to open this document on my IPhone
- Get "document could not be loaded, are you connected to the internet?"
- no Paperless-ngx Server is configured

**Expected behavior**
I can open my document, which was uploaded on my IPad, on my IPhone and vice versa

**Screenshots**

**Environment(please complete the following information):**
 - Device: IPhone15, IPad 7th Gen
 - OS: IOS17.2
 - Version 2.1.2
 - No Server

**Additional context**
Look also at https://github.com/LeoKlaus/Paperparrot/issues/141

**Comment by nerdware-timmmi** [comment] 2024-01-10 12:50
![image](https://github.com/LeoKlaus/Paperparrot/assets/6737248/3fb61ac7-aa23-420f-980f-3b43ed26bedb)

**Comment by LeoKlaus** [comment] 2024-01-10 12:52
Hey JimTim,
Thanks for reaching out!

Sadly, iCloud is very opaque for developers. The OS handles all the syncing, so there could be many reasons for it to fail.

Does the preview image and all other information appear on your iPhone?

Are both devices charged (and not in low-power mode) and connected to Wi-Fi?

Does this apply to all documents or just a few?

**Comment by nerdware-timmmi** [comment] 2024-01-10 14:12
Preview was not shown, but a progress indicator.

So now I have changed both devices to the same network and reupload the document and now the problem disappeared.

So maybe my other WiFi network is slow or sth like this.

Maybe you could add a icloud status information to each document?

Because on the iPad the green status bar appeared that everything was OK when I added it.

**Comment by LeoKlaus** [comment] 2024-01-10 14:23
> So now I have changed both devices to the same network and reupload the document and now the problem disappeared.

Great to hear, thanks for the update!

> Maybe you could add a icloud status information to each document?

This has been on my to-do list for quite some time now. As I said, the syncing process is not really transparent, but I could at least update the error description to be more precise.

> Because on the iPad the green status bar appeared that everything was OK when I added it.

The green status bar just indicates that the document was successfully saved (in case of a "local" configuration with iCloud that just means written to the database and disk).

From there on, the OS has to handle syncing the database, preview image and the actual file via iCloud. These are separate tasks by design.

**Comment by LeoKlaus** [comment] 2024-01-10 14:25
I'll close this for now. If you encounter this issue again, feel free to reopen.

**Closed as completed by LeoKlaus** 2024-01-10 14:25 UTC
Labels: bug
